# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

# Run on pushes to the "main" branch
on:
  push:
    branches: ['main']

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a current LTS version
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        # This command runs "vite build" as defined in your package.json
        # It will use your vite.config.js and output to the /dist folder
        run: npm run build 
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        # This uploads the /dist folder as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Deployment job
  deploy:
    # This job needs the build job to be successful
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # This action does the actual deployment from the artifact
        uses: actions/deploy-pages@v4
